# Use this environment to execute the GLAMR pipelines via Snakemake
name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=9.14
  - snakemake-executor-plugin-cluster-generic=1.0
  - defusedxml=0.7
  - biopython=1.86
  - matplotlib=3.10.8
  - seqkit=2.12 # maybe we can shift the need for this dependency to a rule?
